name: coordinate

run-name: coordinate ${{ inputs.unique_id }}
# gh workflow run \
#   --repo=gulducat/actions-tests \
#   --ref=cross-dispatch coordinate.yaml \
#   --field "ce=$(jq .ce json.json)" \
#   --field "ent=$(jq .ent json.json)"

on:
  #push:
  #  branches: [cross-dispatch]
  workflow_dispatch:
    inputs:
      unique_id:
        type: string
        required: false
      #json: # format: {"ce": [{"source": "main", "dest": "release/1.11.0"}], "ent": []}
      #  type: string
      #  required: true
      ce: # format: [{"source": "main", "dest": "release/1.11.0"}]
        type: string
        required: true
      ent: # format: [{"source": "main", "dest": "release/1.11.0+ent"}]
        type: string
        required: true

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: show inputs
        run: |-
          echo "ce='${{ inputs.ce }}'"
          echo "ent='${{ inputs.ent }}'"

  call-remote-ce:
    needs: [start]
    strategy:
      matrix:
        stuff: ${{ fromJSON(inputs.ce) }}
    uses: gulducat/actions-tests-public/.github/workflows/sleepy.yaml@main # remote repo
    secrets:
      gh_token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
    with:
      repo: gulducat/actions-tests-public
      source_branch: ${{ matrix.stuff.source }}
      dest_branch: ${{ matrix.stuff.dest }}
      prev_version: ${{ matrix.stuff.prev }}

  call-remote-ent:
    needs: [start]
    strategy:
      matrix:
        stuff: ${{ fromJSON(inputs.ent) }}
    uses: gulducat/actions-tests-public/.github/workflows/sleepy.yaml@main # remote repo
    secrets:
      gh_token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
    with:
      repo: gulducat/actions-tests-private
      source_branch: ${{ matrix.stuff.source }}
      dest_branch: ${{ matrix.stuff.dest }}
      prev_version: ${{ matrix.stuff.prev }}

  finish:
    needs:
      - call-remote-ce
      - call-remote-ent
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    # https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows#using-outputs-from-a-reusable-workflow
    #    # If a reusable workflow that sets an output is executed with a matrix strategy, the output will be the output set by the last successful completing reusable workflow of the matrix which actually sets a value.
    #    # so, TODO: artifacts instead of outputs? they're not sensitive...
    #    version: ${{ needs.*.outputs.version }}
    steps:
      - name: pull artifacts
        uses: actions/download-artifact@v5
        with:
          pattern: sleepy-*
          path: ./artifacts
      - name: show artifacts
        run: |-
          tree ./artifacts
          cat ./artifacts/*/*
      - name: done
        run: |-
          echo 'all done: ${{ matrix.version }}'

  dispatch:
    runs-on: ubuntu-latest
    env:
      GH_REPO: gulducat/actions-tests-public
      GH_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: run success
        run: |-
          id="$(date --utc +%s)"
          ./run-and-watch.sh sleepy.yaml "$id" --field "unique_id=$id"
      - name: run fail
        run: |-
          id="$(date --utc +%s)"
          ./run-and-watch.sh sleepy.yaml "$id" --field "unique_id=$id" --field should_fail=true

  #dispatch:
  #  needs: [call-remote-backports]
  #  runs-on: ubuntu-latest
  #  env:
  #    GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
  #    # https://cli.github.com/manual/gh_help_environment
  #    GH_REPO: gulducat/actions-tests-public
  #  steps:
  #    #- name: make an id
  #    #  id: my-id
  #    #  run: echo "id=$(date --utc +%s)" >> $GITHUB_OUTPUTS
  #    - name: dispatch success
  #      run: |-
  #        set -x
  #        this_id=$(date --utc +%s)
  #        gh workflow run \
  #          --ref main \
  #          --field unique_id=$this_id \
  #          --field should_fail=false \
  #          sleepy.yaml
  #        run_id=''
  #        jq_query=".[] | select(.name == \"sleepy ${this_id}\") | .databaseId"
  #        for x in {1..15}; do
  #          run_id=$(gh run list --workflow=sleepy.yaml --jq "${jq_query}" --json name,databaseId)
  #          [ -n "$run_id" ] && break || sleep 2
  #        done
  #        gh run watch --exit-status --compact $run_id
  #    - name: dispatch fail
  #      run: |-
  #        set -x
  #        this_id=$(date --utc +%s)
  #        gh workflow run \
  #          --ref main \
  #          --field unique_id=$this_id \
  #          --field should_fail=true \
  #          sleepy.yaml
  #        run_id=''
  #        jq_query=".[] | select(.name == \"sleepy ${this_id}\") | .databaseId"
  #        for x in {1..15}; do
  #          run_id=$(gh run list --workflow=sleepy.yaml --jq "${jq_query}" --json name,databaseId)
  #          [ -n "$run_id" ] && break || sleep 2
  #        done
  #        gh run watch --exit-status --compact $run_id

