name: coordinate

# gh workflow run \
#   --repo=gulducat/actions-tests \
#   --ref=cross-dispatch coordinate.yaml \
#   --field "ce=$(jq .ce json.json)" \
#   --field "ent=$(jq .ent json.json)"

on:
  #push:
  #  branches: [cross-dispatch]
  workflow_dispatch:
    inputs:
      #json: # format: {"ce": [{"source": "main", "dest": "release/1.11.0"}], "ent": []}
      #  type: string
      #  required: true
      ce: # format: [{"source": "main", "dest": "release/1.11.0"}]
        type: string
        required: true
      ent: # format: [{"source": "main", "dest": "release/1.11.0+ent"}]
        type: string
        required: true

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: show inputs
        run: |-
          echo "ce='${{ inputs.ce }}'"
          echo "ent='${{ inputs.ent }}'"

  call-remote-ce:
    needs: [start]
    strategy:
      matrix:
        stuff: ${{ fromJSON(inputs.ce) }}
    uses: gulducat/actions-tests-public/.github/workflows/sleepy.yaml@main # remote repo
    secrets:
      gh_token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
    with:
      repo: gulducat/actions-tests-public
      source_branch: ${{ matrix.stuff.source }}
      dest_branch: ${{ matrix.stuff.dest }}

  call-remote-ent:
    needs: [start]
    strategy:
      matrix:
        stuff: ${{ fromJSON(inputs.ent) }}
    uses: gulducat/actions-tests-public/.github/workflows/sleepy.yaml@main # remote repo
    secrets:
      gh_token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
    with:
      repo: gulducat/actions-tests-private
      source_branch: ${{ matrix.stuff.source }}
      dest_branch: ${{ matrix.stuff.dest }}

  finish:
    needs:
      - call-remote-ce
      - call-remote-ent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ needs.*.outputs.version }}
    steps:
      - name: done
        run: |-
          echo 'all done: ${{ matrix.version }}'

  #dispatch:
  #  needs: [call-remote-backports]
  #  runs-on: ubuntu-latest
  #  env:
  #    GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
  #    # https://cli.github.com/manual/gh_help_environment
  #    GH_REPO: gulducat/actions-tests-public
  #  steps:
  #    #- name: make an id
  #    #  id: my-id
  #    #  run: echo "id=$(date --utc +%s)" >> $GITHUB_OUTPUTS
  #    - name: dispatch success
  #      run: |-
  #        set -x
  #        this_id=$(date --utc +%s)
  #        gh workflow run \
  #          --ref main \
  #          --field unique_id=$this_id \
  #          --field should_fail=false \
  #          sleepy.yaml
  #        run_id=''
  #        jq_query=".[] | select(.name == \"sleepy ${this_id}\") | .databaseId"
  #        for x in {1..15}; do
  #          run_id=$(gh run list --workflow=sleepy.yaml --jq "${jq_query}" --json name,databaseId)
  #          [ -n "$run_id" ] && break || sleep 2
  #        done
  #        gh run watch --exit-status --compact $run_id
  #    - name: dispatch fail
  #      run: |-
  #        set -x
  #        this_id=$(date --utc +%s)
  #        gh workflow run \
  #          --ref main \
  #          --field unique_id=$this_id \
  #          --field should_fail=true \
  #          sleepy.yaml
  #        run_id=''
  #        jq_query=".[] | select(.name == \"sleepy ${this_id}\") | .databaseId"
  #        for x in {1..15}; do
  #          run_id=$(gh run list --workflow=sleepy.yaml --jq "${jq_query}" --json name,databaseId)
  #          [ -n "$run_id" ] && break || sleep 2
  #        done
  #        gh run watch --exit-status --compact $run_id

