on:
  push:
    branches: [multi-platform]
jobs:
  multi-platform:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: say hello
      run: echo hello
