on:
  push:
    branches: [multi-platform]
jobs:
  multi-platform:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    # this integration test has no external dependencies
    # because it runs its own little fakey http server
    # - name: run integration test
    #   run: go test -v . -tags=integration

    # now to the actual functional tests,
    # which hit real live consul,nomad,vault

    # set up PATH env based on OS
    - name: add bin dir (unix)
      if: runner.os != 'Windows'
      run: echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
    - name: add bin dir (windows)
      if: runner.os == 'Windows'
      run: echo "${env:GITHUB_WORKSPACE}\bin" | Out-File -FilePath ${env:GITHUB_PATH} -Encoding utf8 -Append

    # set up our binaries
    - name: build binary to test
      run: |
        mkdir bin
        go build -o bin
    - name: install softwares
      run: |
        go install github.com/gulducat/hashi-bin@6d44eec
        cd bin
        hashi-bin download consul latest
        hashi-bin download nomad latest
        hashi-bin download vault latest
    - name: check versions
      run: |
        consul version
        nomad version
        vault version

    # run them tests
    - name: run test
      run: go test -v . -tags=functional
